
const CATS=[{n:'Alimentación',e:'🍔'},{n:'Transporte',e:'🚌'},{n:'Ocio',e:'🎬'},{n:'Salud',e:'🏥'},{n:'Educación',e:'📚'},{n:'Salario',e:'💼'}];
let uCats=[...CATS],selCat=null,tipo=null,totIng=4500000,totGas=80600;
const today=new Date().toISOString().split('T')[0];
document.getElementById('f-fecha').value=today;
function upKPIs(){const b=totIng-totGas;document.getElementById('king').textContent='$'+totIng.toLocaleString('es-CO');document.getElementById('kgas').textContent='$'+totGas.toLocaleString('es-CO');document.getElementById('kbal').textContent='$'+b.toLocaleString('es-CO');}
upKPIs();
try{const u=JSON.parse(localStorage.getItem('wbills_user')||'{}');if(u.name){const n=u.name.split(' ')[0];document.getElementById('wname').textContent=n;document.getElementById('topuser').textContent='Hola, '+n;document.getElementById('topav').textContent=n.substring(0,2).toUpperCase();}}catch(e){}
function selectTipo(t){tipo=t;document.getElementById('btn-ing').className='abtn'+(t==='ingreso'?' active-sel':'');document.getElementById('btn-gas').className='abtn'+(t==='gasto'?' active-sel':'');document.getElementById('form-ttl').textContent=t==='ingreso'?'↑ Registrar Ingreso':'↓ Registrar Gasto';document.getElementById('mov-form').classList.add('open');document.getElementById('af').className='af';}
function fmtMonto(inp){let v=inp.value.replace(/\D/g,'');inp.value=v?'$'+parseInt(v).toLocaleString('es-CO'):'';}
function buildCatSel(){const c=document.getElementById('cat-sel');c.innerHTML='';uCats.forEach((cat,i)=>{const d=document.createElement('div');d.className='cs'+(selCat===i?' sel':'');d.innerHTML='<div class="cs-ico">'+cat.e+'</div><div style="font-size:10px">'+cat.n+'</div>';d.onclick=()=>{selCat=i;buildCatSel();document.getElementById('nc-form').classList.remove('open');};c.appendChild(d);});const add=document.createElement('div');add.className='cs cs-add';add.innerHTML='<div class="cs-ico">➕</div><div style="font-size:10px">Nueva</div>';add.onclick=()=>document.getElementById('nc-form').classList.toggle('open');c.appendChild(add);}
buildCatSel();
function addCat(){const n=document.getElementById('nc-name').value.trim(),e=document.getElementById('nc-emoji').value.trim()||'🏷️';if(!n)return;uCats.push({n,e});selCat=uCats.length-1;document.getElementById('nc-name').value='';document.getElementById('nc-emoji').value='';document.getElementById('nc-form').classList.remove('open');buildCatSel();buildCatsG();buildAllList();}
function guardar(){const raw=document.getElementById('f-monto').value.replace(/\D/g,''),desc=document.getElementById('f-desc').value.trim(),fecha=document.getElementById('f-fecha').value,af=document.getElementById('af');
  if(selCat===null){af.textContent='⚠ Selecciona una categoría.';af.className='af err';return;}
  if(!raw){af.textContent='⚠ Ingresa el monto.';af.className='af err';return;}
  if(!fecha){af.textContent='⚠ Selecciona la fecha.';af.className='af err';return;}
  af.className='af';
  const cat=uCats[selCat],esIng=tipo==='ingreso',v=parseInt(raw),fmt=v.toLocaleString('es-CO');
  if(esIng)totIng+=v;else totGas+=v;upKPIs();
  const list=document.getElementById('tx-list'),div=document.createElement('div');div.className='tx';div.setAttribute('data-cat',cat.n);div.style.border=esIng?'1px solid rgba(78,205,196,.2)':'1px solid rgba(224,85,85,.2)';
  div.innerHTML='<div class="tico" style="background:rgba(201,168,76,.08)">'+cat.e+'</div><div class="ti"><div class="tn">'+(desc||cat.n)+'</div><div class="tc2">'+cat.n+'</div></div><div class="ta"><div class="tam '+(esIng?'pos':'neg')+'">'+(esIng?'+':'-')+'$'+fmt+'</div><div class="td">'+fecha+'</div></div>';
  list.insertBefore(div,list.firstChild);
  showAnim(cat.e,(esIng?'Ingreso':'Gasto')+' guardado: $'+fmt,cat.n);
  document.getElementById('f-monto').value='';document.getElementById('f-desc').value='';selCat=null;buildCatSel();}
function showAnim(ico,msg,sub){const ov=document.getElementById('save-ov');document.getElementById('s-ico').textContent=ico||'✅';document.getElementById('s-msg').textContent=msg;document.getElementById('s-sub').textContent=sub;const cf=document.getElementById('cf-wrap');cf.innerHTML='';const cols=['#C9A84C','#F0D080','#4ECDC4','#E05555','#fff'];for(let i=0;i<30;i++){const c=document.createElement('div');c.className='cf';c.style.left=Math.random()*100+'%';c.style.background=cols[Math.floor(Math.random()*cols.length)];c.style.animationDuration=(1+Math.random()*1.2)+'s';c.style.animationDelay=(Math.random()*.4)+'s';cf.appendChild(c);}ov.classList.add('show');setTimeout(()=>ov.classList.remove('show'),2200);}
function closeSave(){document.getElementById('save-ov').classList.remove('show');}
function buildCatsG(){const g=document.getElementById('cats-g');g.innerHTML='';uCats.slice(0,4).forEach(c=>{const d=document.createElement('div');d.className='cat-c';d.innerHTML='<div class="cat-ico2">'+c.e+'</div><div class="cat-nm2">'+c.n+'</div>';d.onclick=()=>showCatH(c.n,c.e,d);g.appendChild(d);});buildAllList();}
buildCatsG();
function buildAllList(){const l=document.getElementById('all-list');l.innerHTML='';uCats.forEach(c=>{const chip=document.createElement('div');chip.style.cssText='display:flex;align-items:center;gap:6px;padding:6px 12px;background:var(--s1);border:1px solid var(--bd);border-radius:20px;font-size:12px;cursor:pointer;transition:border-color .15s';chip.innerHTML=c.e+' '+c.n;chip.onmouseenter=()=>chip.style.borderColor='var(--gold)';chip.onmouseleave=()=>chip.style.borderColor='var(--bd)';chip.onclick=()=>showCatH(c.n,c.e,null);l.appendChild(chip);});}
function toggleAll(){document.getElementById('all-p').classList.toggle('open');}
function showCatH(name,ico,el){document.querySelectorAll('.cat-c').forEach(c=>c.classList.remove('sel-c'));if(el)el.classList.add('sel-c');const all=document.querySelectorAll('#tx-list .tx'),h=document.getElementById('cat-h'),list=document.getElementById('ch-list');document.getElementById('ch-ttl').textContent=ico+' Historial — '+name;list.innerHTML='';let found=0;all.forEach(tx=>{if(tx.getAttribute('data-cat')===name){list.appendChild(tx.cloneNode(true));found++;}});if(!found)list.innerHTML='<div style="font-size:12px;color:var(--mut);padding:8px 0">Sin movimientos en esta categoría.</div>';h.classList.add('open');h.scrollIntoView({behavior:'smooth',block:'nearest'});}
const dBar={mes:{l:['Sem1','Sem2','Sem3','Sem4'],i:[4200,3800,5100,4600],g:[1500,2100,1800,2200]},sem:{l:['Nov','Dic','Ene','Feb','Mar','Abr'],i:[3800,4100,3900,4300,4200,4500],g:[1900,2100,1750,1800,1700,1660]},ano:{l:['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],i:[3900,4300,4200,4500,0,0,0,0,0,0,0,0],g:[1750,1800,1700,1660,0,0,0,0,0,0,0,0]}};
function buildBar(){const tabs=document.getElementById('tabs-bar'),areas=document.getElementById('bar-areas'),vs=[{k:'mes',l:'Este mes'},{k:'sem',l:'6 meses'},{k:'ano',l:'Año'}];tabs.innerHTML='';areas.innerHTML='';vs.forEach((v,idx)=>{const btn=document.createElement('button');btn.className='ctab'+(idx===0?' on':'');btn.textContent=v.l;btn.onclick=()=>{tabs.querySelectorAll('.ctab').forEach(b=>b.classList.remove('on'));btn.classList.add('on');areas.querySelectorAll('.ca').forEach(a=>a.classList.remove('on'));document.getElementById('bar-'+v.k).classList.add('on');};tabs.appendChild(btn);const area=document.createElement('div');area.className='ca'+(idx===0?' on':'');area.id='bar-'+v.k;const d=dBar[v.k],max=Math.max(...d.i);let html='<div class="brs">';d.l.forEach((m,i)=>{const hi=Math.round((d.i[i]/max)*90)||0,hg=Math.round((d.g[i]/max)*90)||0,ha=Math.max(0,Math.round(((d.i[i]-d.g[i])/max)*90));html+='<div class="bc"><div class="bw"><div class="b" style="height:'+hi+'%;background:#4ECDC4"></div><div class="b" style="height:'+hg+'%;background:#E05555"></div><div class="b" style="height:'+ha+'%;background:#C9A84C"></div></div><div class="blbl">'+m+'</div></div>';});html+='</div>';area.innerHTML=html;areas.appendChild(area);});}buildBar();
const dDon={mes:[38,20,17,13,12],sem:[35,22,18,14,11],ano:[34,21,19,15,11]};const dCols=['#FFE66D','#4ECDC4','#E05555','#2ECC71','#8B8070'];const dLbls=['Alimentación','Transporte','Ocio','Salud','Otros'];let dCharts={};
function buildDon(){const tabs=document.getElementById('tabs-don'),areas=document.getElementById('don-areas'),vs=[{k:'mes',l:'Este mes'},{k:'sem',l:'6 meses'},{k:'ano',l:'Año'}];tabs.innerHTML='';areas.innerHTML='';vs.forEach((v,idx)=>{const btn=document.createElement('button');btn.className='ctab'+(idx===0?' on':'');btn.textContent=v.l;btn.onclick=()=>{tabs.querySelectorAll('.ctab').forEach(b=>b.classList.remove('on'));btn.classList.add('on');areas.querySelectorAll('.ca').forEach(a=>a.classList.remove('on'));document.getElementById('don-'+v.k).classList.add('on');};tabs.appendChild(btn);const area=document.createElement('div');area.className='ca'+(idx===0?' on':'');area.id='don-'+v.k;const cid='dc-'+v.k;area.innerHTML='<div class="dw"><canvas id="'+cid+'" width="120" height="120"></canvas><div class="dleg">'+dLbls.map((l,i)=>'<div class="dl"><div class="dd" style="background:'+dCols[i]+'"></div>'+l+'<span class="dp">'+dDon[v.k][i]+'%</span></div>').join('')+'</div></div>';areas.appendChild(area);setTimeout(()=>{const ctx=document.getElementById(cid);if(ctx&&!dCharts[cid]){dCharts[cid]=new Chart(ctx.getContext('2d'),{type:'doughnut',data:{labels:dLbls,datasets:[{data:dDon[v.k],backgroundColor:dCols,borderWidth:0,hoverOffset:5}]},options:{responsive:false,cutout:'65%',plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>c.label+': '+c.parsed+'%'}}}}});}},idx===0?120:0);});}buildDon();

